version: '3.8'

services:
app:
build: .
container_name: my_app_container
ports:
- "8080:8080"
- "2112:2112" # Prometheus metrics port
environment:
- DB_TYPE=postgres
- POSTGRES_HOST=db
- POSTGRES_PORT=5432
- POSTGRES_USER=postgres
- POSTGRES_PASSWORD=password
- POSTGRES_DB=video_db
depends_on:
- db

db:
image: postgres:13
container_name: my_db_container
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: password
POSTGRES_DB: video_db
ports:
- "5432:5432"

mongo:
image: mongo:4.4
container_name: my_mongo_container
environment:
MONGO_INITDB_ROOT_USERNAME: root
MONGO_INITDB_ROOT_PASSWORD: example
ports:
- "27017:27017"

prometheus:
image: prom/prometheus
container_name: prometheus
ports:
- "9090:9090"
volumes:
- ./prometheus.yml:/etc/prometheus/prometheus.yml
