app:
  downloadPath: "path/to/download"
  outputPath: "path/to/output"
  adText: "Your advertisement text"
  adImage: "path/to/ad/image"
  maxConcurrentDownloads: 5
  maxConcurrentUploads: 5
  VEEDKey: "your_veed_api_key"


yt_accounts:
  - apiKey: "AIzaSyBi7MDau60JVC6qaKSrvLUR244UVlIuujs"
    username: "8akebaev@gmail.com"
    category: "20"
    credentials:
      installed:
        project_id: "canty-450309"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        redirect_uris:
          - "http://localhost"


tiktok:
  accounts:
    - apiKey: "your_tiktok_api_key"
      username: "your_tiktok_username"

databases:
  type: "postgres"
  postgres:
    host: "your_postgres_host"
    port: 5432
    user: "postgres"
    password: "postgres"
    dbName: "canty"
  mongo:
    host: "your_mongo_host"
    port: 27017
    user: "your_mongo_user"
    password: "your_mongo_password"
    dbName: "your_mongo_db_name"

monitoring:
  enabled: true

logging:
  log_level: "info"